### PR TITLE
slight change to "color: Y"

### PR DESCRIPTION
**Pull request by umzi2**
I just want you to look. In fact, this option is completely working and has no conversion losses, i.e. we do not convert back and forth, which can reduce the number of conversion losses and remove unnecessary dependencies.

### CODE REVIEW

**Comment by muslll** [comment]
Hi umzi, please make the PR to the `dev` branch instead of master.
Btw, did you test this and it works better than the current solution?

**Comment by umzi2** [comment]
transferred to dev

**Comment by muslll** [comment]
Hi @umzi2, it looks like you accidentally PR'd other changes (to default.py). Could you take those off? I was about to merge this PR, but then saw this...

**Comment by umzi2** [comment]
returned it as it was

**Pull request merged**
